version: '2'
services:
   worker:
      image: dolaterio/dolaterio
      depends_on:
        - rethinkdb
        - redis
        - migrate
      command: /worker
      environment:
        RETHINKDB_PORT_28015_TCP_ADDR: rethinkdb
        REDIS_PORT_6379_TCP_ADDR: redis
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
   api:
      image: dolaterio/dolaterio
      depends_on:
        - rethinkdb
        - redis
        - migrate
      command: /api
      ports:
        - "7000:7000"
      environment:
        BINDING: 0.0.0.0
        RETHINKDB_PORT_28015_TCP_ADDR: rethinkdb
        REDIS_PORT_6379_TCP_ADDR: redis
   migrate:
      image: dolaterio/dolaterio
      environment:
        RETHINKDB_PORT_28015_TCP_ADDR: rethinkdb
      depends_on:
        - rethinkdb
        - redis
      command: /migrate
   redis:
      image: redis:2.8
   rethinkdb:
      image: rethinkdb:2.0
